<a href="https://colab.research.google.com/github/matildadaniela/Book-scraping-project/blob/main/Book_Scraping_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install libraries and load them

In [68]:
!pip install beautifulsoup4
!pip install requests

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)

In [69]:
import requests
from bs4 import BeautifulSoup as bs

#1. Scrape all non-fiction and fiction books

In [86]:
from urllib.parse import urljoin

title_list = []
category_list = []
url_list = []
description_list = []
image_list = []

#fiction book scraping
for i in range (1,5):
  url = f"https://books.toscrape.com/catalogue/category/books/fiction_10/page-{i}.html"
  soup = bs(requests.get(url).content, 'html.parser')
  all_books = soup.find_all('article', class_ = 'product_pod')

  for book in all_books:
    #link
    link = urljoin(url, book.find('h3').find('a')['href'])

    #get to the book page
    book_soup = bs(requests.get(link).content, 'html.parser')

    #title
    title = book.find('h3').find('a')['title']

    #category
    category = book_soup.find('ul', class_='breadcrumb').find_all('a')[2].text.strip()

    #description
    description = book_soup.find('div', id = 'product_description').find_next_sibling('p').text.strip()

    #image
    image = urljoin(link, book_soup.find('div', class_='item active').find('img')['src'])


    title_list.append(title)
    category_list.append(category)
    url_list.append(link)
    description_list.append(description)
    image_list.append(image)

#Nonfiction book scraping
for i in range (1,7):
  url = f"https://books.toscrape.com/catalogue/category/books/nonfiction_13/page-{i}.html"
  soup = bs(requests.get(url).content, 'html.parser')
  all_books = soup.find_all('article', class_ = 'product_pod')

  for book in all_books:
    #link
    link = urljoin(url, book.find('h3').find('a')['href'])

    #get to the book page
    book_soup = bs(requests.get(link).content, 'html.parser')

    #title
    title = book.find('h3').find('a')['title']

    #category
    category = book_soup.find('ul', class_='breadcrumb').find_all('a')[2].text.strip()

    #description
    description = book_soup.find('div', id = 'product_description').find_next_sibling('p').text.strip()

    #image
    image = urljoin(link, book_soup.find('div', class_='item active').find('img')['src'])


    title_list.append(title)
    category_list.append(category)
    url_list.append(link)
    description_list.append(description)
    image_list.append(image)

KeyboardInterrupt:

In [ ]:
import pandas as pd

df_all = pd.DataFrame({'Title': title_list, 'Category': category_list, 'Description': description_list, 'Image': image_list, 'URL': url_list})

# -> CSV
df_all.to_csv('books.csv', index = False)

#2. Data cleaning and analysis

In [101]:
#Examining dataset
df_all.info()
df_all.head()
df_all.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        175 non-null    object
 1   Category     175 non-null    object
 2   Description  175 non-null    object
 3   Image        175 non-null    object
 4   URL          175 non-null    object
dtypes: object(5)
memory usage: 7.0+ KB

,Title,Category,Description,Image,URL
170,H is for Hawk,Nonfiction,When Helen Macdonald's father died suddenly on...,https://books.toscrape.com/media/cache/14/00/1...,https://books.toscrape.com/catalogue/h-is-for-...
171,Travels with Charley: In Search of America,Nonfiction,An intimate journey across and in search of Am...,https://books.toscrape.com/media/cache/3f/c2/3...,https://books.toscrape.com/catalogue/travels-w...
172,The Tumor,Nonfiction,John Grisham says THE TUMOR is the most import...,https://books.toscrape.com/media/cache/8a/14/8...,https://books.toscrape.com/catalogue/the-tumor...
173,The End of the Jesus Era (An Investigation #1),Nonfiction,God exists!? This may seem unprovable. The tru...,https://books.toscrape.com/media/cache/fa/9d/f...,https://books.toscrape.com/catalogue/the-end-o...
174,"Eat, Pray, Love",Nonfiction,"In her early thirties, Elizabeth Gilbert had e...",https://books.toscrape.com/media/cache/5b/82/5...,https://books.toscrape.com/catalogue/eat-pray-...

In [88]:
#Checking for missing values
df_all.isnull().sum()

Title          0
Category       0
Description    0
Image          0
URL            0
dtype: int64

In [90]:
#Checking for duplicates
df_all.duplicated().sum()

np.int64(0)

In [102]:
#Category distribution
df_all['Category'].value_counts()

Category
Nonfiction    110
Fiction        65
Name: count, dtype: int64

In [96]:
#Checking for empty descriptions and titles
print((df_all[['Title', 'Description']] == '').sum())

Title          0
Description    0
dtype: int64

#